version: '3'
services:
  database:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/application
    volumes:
      - ../../../data:/var/lib/postgresql/data/application
    expose:
      - "5432"
  pgadmin:
    image: dpage/pgadmin4:4
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=training@sages.pl
      - PGADMIN_DEFAULT_PASSWORD=123
  tomcat:
    image: 'bitnami/tomcat:latest'
    ports:
      - '8080:8080'
# if tomcat deployment is working very slow, comment out volumes (on osx could work very slow)
# comment out also line: <outputDirectory>./tomcat/data</outputDirectory> in pom.xml
   volumes:
      - /Users/w.zarski/Projects/training/spring-security-2019/spring-training:/bitnami
    environment:
      - TOMCAT_ALLOW_REMOTE_MANAGEMENT=1
    links:
      - database

